spring:
  profiles:
    active: dev
  application:
    name: nt-swagger-starter-example

server:
  port: 2105
#  context-path: /nt-swagger-starter-example

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka