spring:
  profiles:
    active: dev
  application:
    name: nt-config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/redlotus88/NT-Kiseki/tree/develop/nt-config-repo/

server:
  port: 1201