spring:
  profiles:
    active: dev
  application:
    name: nt-config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/redlotus88/NT-Kiseki.git
          search-paths: /nt-config-repo/**
          label: seed
          username: redlotus88
          password: kami4423

server:
  port: 1201

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka