spring:
  profiles:
    active: dev
  application:
    name: nt-config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/redlotus88/NT-Kiseki.git
          search-paths: /nt-config-repo/nt-config-client.yml
          label: seed

server:
  port: 1201