spring:
  application:
    name: nt-eureka-server-cluster

---
#结点 1
spring:
  profiles: discovery1
server:
  port: 8761
eureka:
  instance:
    hostname: discovery1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://discovery2:8762/eureka

---
#结点2
spring:
  profiles: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/

---
##结点3
#spring:
#  profiles: discovery3
#server:
#  port: 8763
#eureka:
#  instance:
#    hostname: discovery3
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://discovery1:8761/eureka/,http://discovery2:8761/eureka/,