spring:
  profiles:
    active: dev
  application:
    name: nt-eureka-server

server:
  port: 8761

eureka:
  # 单机部署
  instance:
    hostname: localhost

  # 禁用自己的客户端注册行为
  client:
    register-with-eureka: false
    fetch-registry: false